const colors = {
  black: '#1a051d',
  blue: '#0084f4',
  blueLight: '#66b5f8',
  blueLighter: '#d5e9fa',
  darkPurple: '#3f3355',
  green: '#00c48c',
  greenDark: '#008055',
  greenLight: '#7ddfc3',
  greenLighter: '#d5f2ea',
  grey: '#d0c9d6',
  greyDark: '#353535',
  greyLight: '#ece9f1',
  greyLighter: '#f7f5f9',
  orange: '#ffa26b',
  orangeDark: '#c34a00',
  orangeLight: '#ffc7a6',
  orangeLighter: '#ffe8da',
  purple: '#8555c5',
  purpleLight: '#dba5f5',
  purpleLighter: '#eedff2',
  red: '#ff647c',
  redDark: '#e00000',
  redLight: '#fdafbb',
  redLighter: '#fbe4e8',
  white: '#fff',
};

const defaultTheme = {
  background: colors.greyLighter,
  border: colors.greyLight,
  borderRadius: '0.25rem',
  borderActive: colors.purple,
  borderToggle: colors.grey,
  boxShadow: '0 6px 64px 0 rgba(0, 0, 0, 0.07)',
  boxShadowHeader: '0 0 10px rgba(0, 0, 0, 0.07)',
  boxShadowSmall: '0 6px 24px rgba(0, 0, 0, 0.07)',
  breakpointS: '600px',
  button: colors.purple,
  buttonActive: colors.darkPurple,
  buttonText: colors.white,
  fontFamilyMono:
    '"Source Code Pro", Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
  footerBackground: colors.purple,
  footerText: colors.white,
  headerBackground: colors.white,
  input: colors.white,
  logoText: colors.purple,
  rangeThumbSize: '1.25rem',
  rangeTrackHeight: '0.25rem',
  text: colors.darkPurple,
  maxWidth: '832px',
  password: {
    good: colors.orange,
    goodBg: colors.orangeLight,
    goodText: colors.orangeDark,
    strong: colors.green,
    strongBg: colors.greenLight,
    strongText: colors.greenDark,
    weak: colors.red,
    weakBg: colors.redLight,
    weakText: colors.redDark,
  },
  toastBg: colors.greyDark,
  toastText: colors.white,
  transition: '0.3s cubic-bezier(1, -0.65, 0, 2.25)',
  transitionEase: '0.3s ease-in-out',
  transitionEaseOut: '0.3s cubic-bezier(0.175, 1, 0.3, 1.35)',
};

export default defaultTheme;
